### PR TITLE
Register username, email, password tooltip.

### PR DESCRIPTION
**Pull request by afrisalyp**
https://github.com/topcoder-platform/community-app/issues/2813
https://github.com/topcoder-platform/community-app/issues/2827

### CODE REVIEW

**Comment by anonymousjaggu** [comment]
@asadath1395 please resolve the conficts

**Comment by afrisalyp** [comment]
@anonymousjaggu Done.

**Comment by afrisalyp** [comment]
> topcoder-platform/community-app#2813: For some reason, when you move to email after listening to the email, it will say again the tooltip for username as well, same if you go on password.

Still investigating. The problem only appears on Chrome. There is a weird behaviour causes it.

>  topcoder-platform/community-app#2827: The special characters are not read by NVDA screen reader. Seems to work with JAWS

I think we don't have control to fix it. NVDA doesn't read the character but JAWS read them.
How should we handle it?

**Comment by afrisalyp** [comment]
@mishacucicea 
Fixed for 

> topcoder-platform/community-app#2813: For some reason, when you move to email after listening to the email, it will say again the tooltip for username as well, same if you go on password.

**Comment by mishacucicea** [comment]
good work

**Comment by nkumar-topcoder** [comment]
reviewer/QA is having different outcomes, hence on-hold

**Comment by mishacucicea** [comment]
@nkumar-topcoder Was this merged on dev/prod?

**Comment by nkumar-topcoder** [comment]
> @nkumar-topcoder Was this merged on dev/prod?

@mishacucicea @afrisalyp    no this isn't merged, because drasticdpk (deepak) review comment. https://github.com/topcoder-platform/community-app/issues/2813#issuecomment-516762806

Can you please review this again and let me know.

**Pull request merged**
