### PR TITLE
Issue 2738 fix

### PR DESCRIPTION
**Pull request by dzanchett**
fixes topcoder-platform/community-app#2738

### CODE REVIEW

**Comment by mishacucicea** [comment]
@dzanchett Have you seen my comment?

**Comment by dzanchett** [comment]
@mishacucicea I saw it, I'll commit the changes in a few minutes.

**Comment by dzanchett** [comment]
@mishacucicea changes on file `app/views/tc/register.jade` are committed.

**Comment by mishacucicea** [comment]
@dzanchett Please resolve the merge conflicts so that I'm able to mark label as Pass.

**Comment by dzanchett** [comment]
@mishacucicea merge conflicts are solved.

**Pull request merged**
