### PR TITLE
MSFT-194-Issue-2860 - added focus to interactive elements

### PR DESCRIPTION
**Pull request by romitgit**
Fixes https://github.com/topcoder-platform/community-app/issues/2860

### CODE REVIEW

**Comment by sexta13** [comment]
can't compile your branch
`ERROR in ./~/css-loader!./~/sass-loader!./app/styles/tc/register.scss
    Module build failed: 
          outline: 2px solid $tc-dark-blue-70;
                            ^
          Undefined variable: "$tc-dark-blue-70".
          in /Users/sexta13/projects/topcoder/accounts-app/app/styles/tc/register.scss (line 50, column 26)`

I believe you are missing this import at the top of register.scss `@import "../tc-ui-variables";`

**Comment by romitgit** [comment]
@sexta13 Fixed now. Please review again. Thanks

**Comment by sexta13** [comment]
@romitgit , please fix the conflicts.

**Comment by sexta13** [comment]
@romitgit , this still is not well done. SSO links are not selectable by tab.

**Comment by sexta13** [comment]
also check this PR https://github.com/appirio-tech/accounts-app/pull/281/files
It puts the tabindex to navigate between the sso_links

**Comment by romitgit** [comment]
@sexta13 Fixed changes.

**Comment by mtwomey** [comment]
This already appears corrected in production?

**Comment by romitgit** [comment]
But It wasn't there already.

**Comment by nkumar-topcoder** [comment]
Closing PR as it's already in prod

**Pull request closed without merging**
