### PR TITLE
trigger-deploy-cache

### PR DESCRIPTION
**Pull request by maxceem**

### CODE REVIEW

**Comment by RishiRajSahu** [comment]
@maxceem could you remove the branch from deployable, I will merge after that.

**Comment by maxceem** [comment]
@RishiRajSahu I've removed this branch from deployable, but we already `package.json` reverted in this branch. So by fact, now it doesn't have any changes in comparison with `dev`. I guess we have to make some changes to `package.json` so merging this branch would trigger `dev` cache clearing.

**Comment by maxceem** [comment]
@RishiRajSahu I've added a trivial change to `package.json`.

**Comment by RishiRajSahu** [comment]
@maxceem merging to test new registration on dev.

**Comment by RishiRajSahu** [comment]
@maxceem merging to test new registration on dev.

**Pull request merged**
