### PR TITLE
MSFT-88

### PR DESCRIPTION
**Pull request by r0hit-gupta**
changes for https://github.com/topcoder-platform/community-app/issues/2798

### CODE REVIEW

**Comment by mishacucicea** [comment]
@r0hit-gupta Were this items fixed as part of other branches, as you have only one small file changed, it can't fix all these issues.

**Comment by r0hit-gupta** [comment]
@mishacucicea all those issues had the same solution. So, as I went through the issues, I realised this and referenced them under the same PR. This PR fixes all of the issues.

**Comment by mishacucicea** [comment]
@r0hit-gupta Please reference the solution from existing fixes for each issue.

**Comment by r0hit-gupta** [comment]
@mishacucicea I have already referenced the PR from each individual issue.

**Comment by mishacucicea** [comment]
topcoder-platform/community-app#2798 - not working, it's expected that the color changes when using the tab key, which means on :focus
topcoder-platform/community-app#2800,  topcoder-platform/community-app#2875 - not working, I don't see any highlight when using tab key.

**Comment by mishacucicea** [comment]
@r0hit-gupta Did you put all needed file changes in this PR? Perhaps you missed some.

**Comment by r0hit-gupta** [comment]
@mishacucicea I updated the code to change color on tab key for privacy policy. 
For other issues, is there any particular element for which the highlight is not visible? Because the fix is working fine for me.

**Comment by mishacucicea** [comment]
@r0hit-gupta  The issue you're fixing is https://github.com/topcoder-platform/community-app/issues/2798.
The other issues are not fixed by this PR (If something doesn't work, I need to revert the PR, and in this case I can see it's related and fixing only one issue).

**Comment by r0hit-gupta** [comment]
@mishacucicea I have unlinked other issues. Will create a separate PR for them. Please review.

**Comment by r0hit-gupta** [comment]
@mishacucicea done. Please review.

**Pull request merged**
