### PR TITLE
issue 2868 fix

### PR DESCRIPTION
**Pull request by PrakashDurlabhji**

### CODE REVIEW

**Comment by nkumar-topcoder** [comment]
change PR to appirio-tech:qa-accessibility

**Comment by PrakashDurlabhji** [comment]
@mishacucicea PR updated

**Comment by mishacucicea** [comment]
@PrakashDurlabhji Please don't use hardcoded values for colors, they are already present in `tc-ui-variables.scss`. Reference that file and use variable name.

**Comment by PrakashDurlabhji** [comment]
@veshu @mishacucicea PR updated. not able to change the label else it is completed.

**Comment by mishacucicea** [comment]
@PrakashDurlabhji Your code is not compiling, you need to reference tc-ui-variables.scss

Please make sure you thoroughly check your PRs and changes, otherwise we won't accept your submissions and the level of trust in your code will decrease.

**Comment by PrakashDurlabhji** [comment]
@mishacucicea chcking

**Comment by PrakashDurlabhji** [comment]
@mishacucicea updated

**Comment by mishacucicea** [comment]
Undefined variable: "$tc-dark-blue-70". Fix it

**Comment by PrakashDurlabhji** [comment]
@mishacucicea isnt a PR merged in it which inserted $tc-dark-blue-70, so i used it assuming it will be present in code till my code is reviewed. I guess it is not yet inside yet.

**Comment by mishacucicea** [comment]
@PrakashDurlabhji You need to make sure that the current branch, (e.g. issue_2868) is working OK, which, at the time being it doesn't. Currently it shows that these are your changes compared to the qa-accessibility branch. Even if the import was added in another place, if it's not on the qa-accessibility branch you need to fix it.
I'm curious how did you tested locally, you do know changes need to be tested before requesting a review, right?

**Comment by PrakashDurlabhji** [comment]
@mishacucicea PR updated with screenshot on issue page and no compilation error now. kindly provide feedback if anything left will confirm everything with screenshot from nowon

**Pull request merged**
